// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createFarm = `-- name: CreateFarm :one
INSERT INTO farm (
  firmware_version
) VALUES (
  $1
)
RETURNING id, firmware_version, created_at, updated_at
`

func (q *Queries) CreateFarm(ctx context.Context, firmwareVersion string) (Farm, error) {
	row := q.db.QueryRow(ctx, createFarm, firmwareVersion)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFirmware = `-- name: CreateFirmware :one
INSERT INTO firmware (
  version, url
) VALUES (
  $1, $2
)
RETURNING version, url, created_at
`

type CreateFirmwareParams struct {
	Version string `json:"version"`
	Url     string `json:"url"`
}

func (q *Queries) CreateFirmware(ctx context.Context, arg CreateFirmwareParams) (Firmware, error) {
	row := q.db.QueryRow(ctx, createFirmware, arg.Version, arg.Url)
	var i Firmware
	err := row.Scan(&i.Version, &i.Url, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, email
) VALUES (
  $1, $2
)
RETURNING id, name, email, created_at
`

type CreateUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFarmById = `-- name: DeleteFarmById :exec
DELETE FROM farm WHERE id = $1
`

func (q *Queries) DeleteFarmById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFarmById, id)
	return err
}

const getFarmById = `-- name: GetFarmById :one
SELECT id, firmware_version, created_at, updated_at FROM farm WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFarmById(ctx context.Context, id int64) (Farm, error) {
	row := q.db.QueryRow(ctx, getFarmById, id)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFarms = `-- name: GetFarms :many
SELECT id, firmware_version, created_at, updated_at FROM farm
`

func (q *Queries) GetFarms(ctx context.Context) ([]Farm, error) {
	rows, err := q.db.Query(ctx, getFarms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Farm
	for rows.Next() {
		var i Farm
		if err := rows.Scan(
			&i.ID,
			&i.FirmwareVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirmwareByVersion = `-- name: GetFirmwareByVersion :one
SELECT version, url, created_at FROM firmware WHERE version = $1 LIMIT 1
`

func (q *Queries) GetFirmwareByVersion(ctx context.Context, version string) (Firmware, error) {
	row := q.db.QueryRow(ctx, getFirmwareByVersion, version)
	var i Firmware
	err := row.Scan(&i.Version, &i.Url, &i.CreatedAt)
	return i, err
}

const getFirmwares = `-- name: GetFirmwares :many
SELECT version, url, created_at FROM firmware
`

func (q *Queries) GetFirmwares(ctx context.Context) ([]Firmware, error) {
	rows, err := q.db.Query(ctx, getFirmwares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Firmware
	for rows.Next() {
		var i Firmware
		if err := rows.Scan(&i.Version, &i.Url, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastFirmware = `-- name: GetLastFirmware :one
SELECT version, url, created_at FROM firmware ORDER BY created_at DESC  LIMIT 1
`

func (q *Queries) GetLastFirmware(ctx context.Context) (Firmware, error) {
	row := q.db.QueryRow(ctx, getLastFirmware)
	var i Firmware
	err := row.Scan(&i.Version, &i.Url, &i.CreatedAt)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, created_at FROM users WHERE Id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, email, created_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFarmVersion = `-- name: UpdateFarmVersion :one
UPDATE farm
  set firmware_version = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, firmware_version, created_at, updated_at
`

type UpdateFarmVersionParams struct {
	ID              int64  `json:"id"`
	FirmwareVersion string `json:"firmware_version"`
}

func (q *Queries) UpdateFarmVersion(ctx context.Context, arg UpdateFarmVersionParams) (Farm, error) {
	row := q.db.QueryRow(ctx, updateFarmVersion, arg.ID, arg.FirmwareVersion)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.FirmwareVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
