// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
