// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createFirmware = `-- name: CreateFirmware :one
INSERT INTO firmware (
  version, url
) VALUES (
  $1, $2
)
RETURNING version, url, created_at
`

type CreateFirmwareParams struct {
	Version string `json:"version"`
	Url     string `json:"url"`
}

func (q *Queries) CreateFirmware(ctx context.Context, arg CreateFirmwareParams) (Firmware, error) {
	row := q.db.QueryRow(ctx, createFirmware, arg.Version, arg.Url)
	var i Firmware
	err := row.Scan(&i.Version, &i.Url, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, email
) VALUES (
  $1, $2
)
RETURNING id, name, email, created_at
`

type CreateUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getFirmwareByVersion = `-- name: GetFirmwareByVersion :one
SELECT version, url, created_at FROM firmware WHERE version = $1 LIMIT 1
`

func (q *Queries) GetFirmwareByVersion(ctx context.Context, version string) (Firmware, error) {
	row := q.db.QueryRow(ctx, getFirmwareByVersion, version)
	var i Firmware
	err := row.Scan(&i.Version, &i.Url, &i.CreatedAt)
	return i, err
}

const getFirmwares = `-- name: GetFirmwares :many
SELECT version, url, created_at FROM firmware
`

func (q *Queries) GetFirmwares(ctx context.Context) ([]Firmware, error) {
	rows, err := q.db.Query(ctx, getFirmwares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Firmware
	for rows.Next() {
		var i Firmware
		if err := rows.Scan(&i.Version, &i.Url, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastFirmware = `-- name: GetLastFirmware :one
SELECT version, url, created_at FROM firmware ORDER BY created_at DESC  LIMIT 1
`

func (q *Queries) GetLastFirmware(ctx context.Context) (Firmware, error) {
	row := q.db.QueryRow(ctx, getLastFirmware)
	var i Firmware
	err := row.Scan(&i.Version, &i.Url, &i.CreatedAt)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, created_at FROM users WHERE Id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, email, created_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
