// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateFarm(ctx context.Context, firmwareVersion string) (Farm, error)
	CreateFirmware(ctx context.Context, arg CreateFirmwareParams) (Firmware, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetFirmwareByVersion(ctx context.Context, version string) (Firmware, error)
	GetFirmwares(ctx context.Context) ([]Firmware, error)
	GetLastFirmware(ctx context.Context) (Firmware, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
